# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
APPLY_FIXES: all # all, none, or list of linter keys
ENABLE_LINTERS:
    - PYTHON_RUFF
    - PYTHON_ISORT
      #- SPELL
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

